apiVersion: v2
name: spaceone
description: A Helm chart for SpaceONE

type: application
version: "1.6.7"
appVersion: "1.6.7"

home: https://www.spaceone.org

dependencies:
    - name: console
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: console.enabled
    - name: console-api
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: console-api.enabled
    - name: identity
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: identity.enabled
    - name: secret
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: secret.enabled
    - name: repository
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: repository.enabled
    - name: plugin
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: plugin.enabled
    - name: config
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: config.enabled
    - name: inventory
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: inventory.enabled
    - name: monitoring
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: monitoring.enabled
    - name: statistics
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: statistics.enabled
    - name: billing
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: billing.enabled
    - name: power-scheduler
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: power-scheduler.enabled
    - name: cost-saving
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: cost-saving.enabled
    - name: spot-automation
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: spot-automation.enabled

    - name: marketplace-assets
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: marketplace-assets.enabled
  
    - name: supervisor
      version: "1.1.2"
      repository: https://spaceone-dev.github.io/charts
      condition: supervisor.enabled

    - name: spaceone-initializer
      version: ">=1.0.0"
      repository: https://spaceone-dev.github.io/charts
      condition: supervisor.enabled

    - name: vault
      version: ">=0.1.0"
      condition: vault.enabled
